name: WHOAMI

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:

  run-analysis:
    name: info
    runs-on: ubuntu-latest
    steps:

      - name: who am i
        run: echo ${{ github.actor }}

